"""info add title2

Revision ID: 0beed2640691
Revises: 63d99b00ad8a
Create Date: 2021-04-09 09:01:30.248133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0beed2640691'
down_revision = '63d99b00ad8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('title2', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info', 'title2')
    # ### end Alembic commands ###
