# Generated by Django 3.0.3 on 2020-02-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='AA',
            field=models.CharField(default='', max_length=200),
        ),
    ]
