# Generated by Django 3.0.3 on 2020-02-19 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_post_aa'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='creat_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立日期'),
        ),
    ]
