# Generated by Django 3.0.3 on 2020-02-19 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_store_creat_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='creat_dt',
            new_name='create_dt',
        ),
    ]
