# Generated by Django 3.0.3 on 2020-02-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_store_url_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='url_logo',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
