# Generated by Django 3.0.3 on 2020-02-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20200219_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='url_href',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='url_logo',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
