# Generated by Django 3.0.3 on 2020-02-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20200221_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='url_logo',
            field=models.URLField(blank=True, default=''),
        ),
    ]
