# Generated by Django 3.0.3 on 2020-02-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20200221_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.URLField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='store',
            name='url_logo',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
