# Generated by Django 3.0.3 on 2020-02-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20200221_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='store',
            name='url_href',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
