# Generated by Django 3.0.3 on 2020-02-21 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0031_store_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('code',)},
        ),
    ]
