# Generated by Django 3.0.3 on 2020-02-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0032_auto_20200221_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(default='0123456789', max_length=10)),
                ('isbn', models.CharField(default='9789571234567', max_length=13)),
                ('title', models.CharField(default='書名', max_length=200)),
                ('author', models.CharField(default='作者', max_length=200)),
                ('publisher', models.CharField(default='出版社', max_length=200)),
            ],
            options={
                'ordering': ('bookid',),
            },
        ),
    ]
