# Generated by Django 3.0.3 on 2020-02-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0035_auto_20200227_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bookid',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='isbn',
            field=models.CharField(default='', max_length=13),
        ),
    ]
