# Generated by Django 3.0.3 on 2020-02-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0036_auto_20200227_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='url_cover',
            field=models.URLField(blank=True, default=None),
        ),
    ]
