# Generated by Django 3.0.3 on 2020-02-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0037_bookinfo_url_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='err',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='url_cover',
            field=models.URLField(blank=True, default=''),
        ),
    ]
