# Generated by Django 3.0.3 on 2020-02-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0048_auto_20200227_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
