# Generated by Django 3.0.3 on 2020-02-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0076_auto_20200227_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
