# Generated by Django 3.0.3 on 2020-02-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0089_auto_20200227_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='err',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
