# Generated by Django 3.0.3 on 2020-02-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0092_auto_20200227_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='err',
            field=models.CharField(blank=True, default='qq', max_length=100),
        ),
    ]
