# Generated by Django 3.0.3 on 2020-02-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0094_auto_20200227_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
