# Generated by Django 3.0.3 on 2020-02-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0096_auto_20200227_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bookid',
            field=models.CharField(blank=True, default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
