# Generated by Django 3.0.3 on 2020-02-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0099_bookinfo_pub_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='lang',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
