# Generated by Django 3.0.3 on 2020-02-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0100_bookinfo_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='pub_dt',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='出版日期'),
        ),
    ]
