# Generated by Django 3.0.3 on 2020-02-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0101_auto_20200228_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='create_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
