# Generated by Django 3.0.3 on 2020-02-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0102_bookinfo_create_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='create_dt',
            field=models.DateTimeField(default=None, verbose_name='更新日期'),
        ),
    ]
