# Generated by Django 3.0.3 on 2020-02-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0103_auto_20200228_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='create_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
