# Generated by Django 3.0.3 on 2020-02-28 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0104_auto_20200228_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='create_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日期'),
        ),
    ]
