# Generated by Django 3.0.3 on 2020-03-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0106_bookprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='price_list',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='price_sale',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
