# Generated by Django 3.0.3 on 2020-03-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0107_auto_20200302_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprice',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
