# Generated by Django 3.0.3 on 2020-03-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0110_bookprice_url_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprice',
            name='price_sale_ebook',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
