# Generated by Django 3.0.3 on 2020-03-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0114_auto_20200303_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='bookid_ebook',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='price_sale_ebook',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
