# Generated by Django 3.0.3 on 2020-03-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0115_auto_20200303_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='spec',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
