# Generated by Django 3.0.3 on 2020-03-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0117_bookinfo_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='isbn13',
            field=models.CharField(blank=True, default='', max_length=13),
        ),
    ]
