# Generated by Django 3.0.3 on 2020-03-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0120_bookinfo_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='url_vdo',
            field=models.URLField(blank=True, default=''),
        ),
    ]
