# Generated by Django 3.0.3 on 2020-03-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0122_bookprice_url_vdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookprice',
            name='stock',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
