# Generated by Django 3.0.3 on 2020-03-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0125_auto_20200322_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookprice',
            options={'ordering': ('-create_dt',)},
        ),
        migrations.AddField(
            model_name='store',
            name='enable',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
