"""create ips info

Revision ID: 62a14ae0dd3c
Revises: 
Create Date: 2021-05-01 13:27:19.508245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a14ae0dd3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store', sa.String(), nullable=True),
    sa.Column('bookid', sa.String(), nullable=True),
    sa.Column('isbn10', sa.String(), nullable=True),
    sa.Column('isbn13', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title2', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('pub_dt', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('ips',
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('port', sa.String(), nullable=False),
    sa.Column('now', sa.String(), nullable=False),
    sa.Column('goodcnt', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ips')
    op.drop_table('info')
    # ### end Alembic commands ###
