"""idx

Revision ID: 91eb815babd3
Revises: 
Create Date: 2021-04-09 16:47:59.714915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91eb815babd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('title2', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('ips',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('port', sa.String(), nullable=False),
    sa.Column('now', sa.String(), nullable=False),
    sa.Column('goodcnt', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ips')
    op.drop_table('info')
    # ### end Alembic commands ###
