"""create test tb

Revision ID: 11472b309f81
Revises: ef9455f10043
Create Date: 2021-04-08 20:03:01.621279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11472b309f81'
down_revision = 'ef9455f10043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
                    sa.Column('ip', sa.String(), nullable=False),
                    sa.Column('port', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('ip')
                    )
    # op.drop_table('fruits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('fruits',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='fruits_pkey')
    # )
    op.drop_table('test')
    # ### end Alembic commands ###
