#搜尋故意少博客來 
url_qs={
        'elite':"http://www.eslite.com/Search_BW.aspx?searchType=&query=",
        'ks':"https://www.kingstone.com.tw/search/search?q=",
        #'momo':"https://www.momoshop.com.tw/search/searchShop.jsp?keyword="
        #momo用手機板查
        'momo':"https://m.momoshop.com.tw/search.momo?searchKeyword=",
        'taaze':"https://www.taaze.tw/rwd_searchResult.html?keyType%5B%5D=0&keyword%5B%5D=",
        'mollie':'http://www.mollie.com.tw/Mobile/Books.asp',
        'iread':'https://www.iread.com.tw/search_results.aspx?Condition=0&skeyword=',
        'cite':'https://www.cite.com.tw/search_result?keywords=',
        'tenlong':'https://www.tenlong.com.tw/search?keyword=',
        'ruten':'https://find.ruten.com.tw/s/?q=',
        'sanmin':'https://www.sanmin.com.tw/search/index/?ct=ISBN&ls=SD&qu=',
        'yahoo':'https://tw.bid.yahoo.com/search/auction/product?sort=curp&p=',
        'shopee':'https://shopee.tw/search?keyword=',
        'linking':'https://www.linkingbooks.com.tw/LNB/SearchBook.aspx?ID=&text=',
        'cwgv':'https://bookzone.cwgv.com.tw/search/index/',
        'rtimes':'http://www.readingtimes.com.tw/ReadingTimes/site/q__9789571380049/414/default.aspx',
    }
#顯示在svg的店家名稱
store_names=['博客來','誠品','金石堂','momo','讀冊','茉莉','灰熊','城邦','天瓏','露天','三民','Y拍','蝦皮','聯經','天下','時報']
#顯示在svg的店家官網
store_urls=[
    'https://www.books.com.tw/',
    'http://www.eslite.com/',
    'https://www.kingstone.com.tw/',
    'https://www.momoshop.com.tw/main/Main.jsp',
    'https://www.taaze.tw/index.html',
    'http://www.mollie.com.tw/News_List.asp',
    'https://www.iread.com.tw/index.aspx',
    'https://www.cite.com.tw/',
    'https://www.tenlong.com.tw/',
    'https://www.ruten.com.tw/',
    'https://www.sanmin.com.tw/home/index',
    'https://tw.bid.yahoo.com/',
    'https://shopee.tw/',
    'https://www.linkingbooks.com.tw/LNB/index.aspx',
    'https://bookzone.cwgv.com.tw/home/index',
    'http://www.readingtimes.com.tw/ReadingTimes/default.aspx',
]